<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Anaconda.Kernel</AssemblyName>
    <RootNamespace>Anaconda.Kernel</RootNamespace>
  </PropertyGroup>

</Project>
